

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Puspita Rahayu
 */
public class transaks extends javax.swing.JFrame {
    private int membayar,jumlah,kembali;
    
    public transaks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nasgor = new javax.swing.JTextField();
        nasgormawut = new javax.swing.JTextField();
        miegor = new javax.swing.JTextField();
        capcay = new javax.swing.JTextField();
        miecapcay = new javax.swing.JTextField();
        miebakso = new javax.swing.JTextField();
        NASGOR = new javax.swing.JCheckBox();
        NASGORMAWUT = new javax.swing.JCheckBox();
        MIEGOR = new javax.swing.JCheckBox();
        CAPCAY = new javax.swing.JCheckBox();
        MIECAPCAY = new javax.swing.JCheckBox();
        MIEBAKSO = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jamur = new javax.swing.JTextField();
        bakso = new javax.swing.JTextField();
        ati = new javax.swing.JTextField();
        sosis = new javax.swing.JTextField();
        usus = new javax.swing.JTextField();
        telur = new javax.swing.JTextField();
        kikil = new javax.swing.JTextField();
        pete = new javax.swing.JTextField();
        abon = new javax.swing.JTextField();
        JAMUR = new javax.swing.JCheckBox();
        BAKSO = new javax.swing.JCheckBox();
        ATI = new javax.swing.JCheckBox();
        SOSIS = new javax.swing.JCheckBox();
        USUS = new javax.swing.JCheckBox();
        TELUR = new javax.swing.JCheckBox();
        KIKIL = new javax.swing.JCheckBox();
        PETE = new javax.swing.JCheckBox();
        ABON = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jeruk = new javax.swing.JTextField();
        teh = new javax.swing.JTextField();
        susu = new javax.swing.JTextField();
        jahe = new javax.swing.JTextField();
        jahekrim = new javax.swing.JTextField();
        joshua = new javax.swing.JTextField();
        stmj = new javax.swing.JTextField();
        soda = new javax.swing.JTextField();
        JERUK = new javax.swing.JCheckBox();
        TEH = new javax.swing.JCheckBox();
        SUSU = new javax.swing.JCheckBox();
        JAHE = new javax.swing.JCheckBox();
        JAHEKRIM = new javax.swing.JCheckBox();
        JOSHUA = new javax.swing.JCheckBox();
        STMJ = new javax.swing.JCheckBox();
        SODA = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        kopi = new javax.swing.JTextField();
        kopisusu = new javax.swing.JTextField();
        kopistmj = new javax.swing.JTextField();
        kopibro = new javax.swing.JTextField();
        kopimocha = new javax.swing.JTextField();
        kopicap = new javax.swing.JTextField();
        kopigingseng = new javax.swing.JTextField();
        KOPIGINGSENG = new javax.swing.JCheckBox();
        KOPI = new javax.swing.JCheckBox();
        KOPISUSU = new javax.swing.JCheckBox();
        KOPISTMJ = new javax.swing.JCheckBox();
        KOPIBRO = new javax.swing.JCheckBox();
        KOPIMOCHA = new javax.swing.JCheckBox();
        KOPICAP = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Bayar = new javax.swing.JButton();
        textHitung = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        textBayar = new javax.swing.JTextField();
        Kembali = new javax.swing.JButton();
        textKembali = new javax.swing.JTextField();
        Hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorActionPerformed(evt);
            }
        });
        jPanel1.add(nasgor);
        nasgor.setBounds(150, 20, 42, 32);
        jPanel1.add(nasgormawut);
        nasgormawut.setBounds(150, 60, 42, 32);
        jPanel1.add(miegor);
        miegor.setBounds(150, 100, 42, 32);
        jPanel1.add(capcay);
        capcay.setBounds(150, 140, 42, 32);
        jPanel1.add(miecapcay);
        miecapcay.setBounds(150, 180, 42, 32);
        jPanel1.add(miebakso);
        miebakso.setBounds(150, 220, 42, 32);

        NASGOR.setText("Nasi Goreng");
        NASGOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NASGORActionPerformed(evt);
            }
        });
        jPanel1.add(NASGOR);
        NASGOR.setBounds(20, 20, 120, 30);

        NASGORMAWUT.setText("Nasi Goreng Mawut");
        NASGORMAWUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NASGORMAWUTActionPerformed(evt);
            }
        });
        jPanel1.add(NASGORMAWUT);
        NASGORMAWUT.setBounds(20, 60, 120, 30);

        MIEGOR.setText("Mie Goreng / Kuah");
        MIEGOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIEGORActionPerformed(evt);
            }
        });
        jPanel1.add(MIEGOR);
        MIEGOR.setBounds(20, 100, 120, 30);

        CAPCAY.setText("Capcay");
        CAPCAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAPCAYActionPerformed(evt);
            }
        });
        jPanel1.add(CAPCAY);
        CAPCAY.setBounds(20, 140, 120, 30);

        MIECAPCAY.setText("Mie Capcay");
        MIECAPCAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIECAPCAYActionPerformed(evt);
            }
        });
        jPanel1.add(MIECAPCAY);
        MIECAPCAY.setBounds(20, 180, 120, 30);

        MIEBAKSO.setText("Mie Bakso");
        MIEBAKSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIEBAKSOActionPerformed(evt);
            }
        });
        jPanel1.add(MIEBAKSO);
        MIEBAKSO.setBounds(20, 220, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 220, 370);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);
        jPanel2.add(jamur);
        jamur.setBounds(169, 22, 42, 32);
        jPanel2.add(bakso);
        bakso.setBounds(169, 60, 42, 32);
        jPanel2.add(ati);
        ati.setBounds(169, 98, 42, 32);
        jPanel2.add(sosis);
        sosis.setBounds(170, 140, 42, 32);
        jPanel2.add(usus);
        usus.setBounds(170, 180, 42, 32);
        jPanel2.add(telur);
        telur.setBounds(170, 220, 42, 32);
        jPanel2.add(kikil);
        kikil.setBounds(170, 260, 42, 32);
        jPanel2.add(pete);
        pete.setBounds(170, 300, 42, 32);
        jPanel2.add(abon);
        abon.setBounds(170, 340, 42, 32);

        JAMUR.setText("Jamur Crispy");
        JAMUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAMURActionPerformed(evt);
            }
        });
        jPanel2.add(JAMUR);
        JAMUR.setBounds(20, 20, 120, 30);

        BAKSO.setText("Bakso Daging");
        BAKSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAKSOActionPerformed(evt);
            }
        });
        jPanel2.add(BAKSO);
        BAKSO.setBounds(20, 60, 120, 30);

        ATI.setText("Rempelo Ati Ayam");
        ATI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATIActionPerformed(evt);
            }
        });
        jPanel2.add(ATI);
        ATI.setBounds(20, 100, 120, 30);

        SOSIS.setText("Sosis");
        SOSIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOSISActionPerformed(evt);
            }
        });
        jPanel2.add(SOSIS);
        SOSIS.setBounds(20, 140, 120, 30);

        USUS.setText("Usus Crispy");
        USUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USUSActionPerformed(evt);
            }
        });
        jPanel2.add(USUS);
        USUS.setBounds(20, 180, 120, 30);

        TELUR.setText("Telus Dadar / Ceplok");
        TELUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TELURActionPerformed(evt);
            }
        });
        jPanel2.add(TELUR);
        TELUR.setBounds(20, 220, 140, 30);

        KIKIL.setText("Kikil");
        KIKIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KIKILActionPerformed(evt);
            }
        });
        jPanel2.add(KIKIL);
        KIKIL.setBounds(20, 260, 120, 30);

        PETE.setText("Pete");
        PETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PETEActionPerformed(evt);
            }
        });
        jPanel2.add(PETE);
        PETE.setBounds(20, 300, 120, 30);

        ABON.setText("Abon Daging");
        ABON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABONActionPerformed(evt);
            }
        });
        jPanel2.add(ABON);
        ABON.setBounds(20, 340, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 100, 220, 390);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(null);
        jPanel3.add(jeruk);
        jeruk.setBounds(170, 20, 42, 32);
        jPanel3.add(teh);
        teh.setBounds(169, 60, 42, 32);
        jPanel3.add(susu);
        susu.setBounds(169, 98, 42, 32);
        jPanel3.add(jahe);
        jahe.setBounds(170, 140, 42, 32);
        jPanel3.add(jahekrim);
        jahekrim.setBounds(170, 180, 42, 32);
        jPanel3.add(joshua);
        joshua.setBounds(170, 220, 42, 32);
        jPanel3.add(stmj);
        stmj.setBounds(170, 260, 42, 32);
        jPanel3.add(soda);
        soda.setBounds(170, 300, 42, 32);

        JERUK.setText("Jeruk");
        JERUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JERUKActionPerformed(evt);
            }
        });
        jPanel3.add(JERUK);
        JERUK.setBounds(30, 20, 120, 30);

        TEH.setText("Teh");
        TEH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEHActionPerformed(evt);
            }
        });
        jPanel3.add(TEH);
        TEH.setBounds(30, 60, 120, 30);

        SUSU.setText("Susu");
        SUSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUSUActionPerformed(evt);
            }
        });
        jPanel3.add(SUSU);
        SUSU.setBounds(30, 100, 120, 30);

        JAHE.setText("Jahe");
        JAHE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAHEActionPerformed(evt);
            }
        });
        jPanel3.add(JAHE);
        JAHE.setBounds(30, 140, 120, 30);

        JAHEKRIM.setText("Jahe + Krim");
        JAHEKRIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAHEKRIMActionPerformed(evt);
            }
        });
        jPanel3.add(JAHEKRIM);
        JAHEKRIM.setBounds(30, 180, 120, 30);

        JOSHUA.setText("Joshua");
        JOSHUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOSHUAActionPerformed(evt);
            }
        });
        jPanel3.add(JOSHUA);
        JOSHUA.setBounds(30, 220, 120, 30);

        STMJ.setText("STMJ");
        STMJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STMJActionPerformed(evt);
            }
        });
        jPanel3.add(STMJ);
        STMJ.setBounds(30, 260, 120, 30);

        SODA.setText("Soda Gembira");
        SODA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SODAActionPerformed(evt);
            }
        });
        jPanel3.add(SODA);
        SODA.setBounds(30, 300, 120, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(470, 100, 220, 370);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(null);
        jPanel4.add(kopi);
        kopi.setBounds(170, 20, 42, 32);
        jPanel4.add(kopisusu);
        kopisusu.setBounds(169, 60, 42, 32);
        jPanel4.add(kopistmj);
        kopistmj.setBounds(169, 98, 42, 32);
        jPanel4.add(kopibro);
        kopibro.setBounds(170, 140, 42, 32);
        jPanel4.add(kopimocha);
        kopimocha.setBounds(170, 180, 42, 32);
        jPanel4.add(kopicap);
        kopicap.setBounds(170, 220, 42, 32);
        jPanel4.add(kopigingseng);
        kopigingseng.setBounds(170, 260, 42, 32);

        KOPIGINGSENG.setText("Kopi Gingseng");
        KOPIGINGSENG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPIGINGSENGActionPerformed(evt);
            }
        });
        jPanel4.add(KOPIGINGSENG);
        KOPIGINGSENG.setBounds(30, 260, 120, 30);

        KOPI.setText("Kopi");
        KOPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPIActionPerformed(evt);
            }
        });
        jPanel4.add(KOPI);
        KOPI.setBounds(30, 20, 120, 30);

        KOPISUSU.setText("Kopi Susu");
        KOPISUSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPISUSUActionPerformed(evt);
            }
        });
        jPanel4.add(KOPISUSU);
        KOPISUSU.setBounds(30, 60, 120, 30);

        KOPISTMJ.setText("Kopi STMJ");
        KOPISTMJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPISTMJActionPerformed(evt);
            }
        });
        jPanel4.add(KOPISTMJ);
        KOPISTMJ.setBounds(30, 100, 120, 30);

        KOPIBRO.setText("Kopi Brownies");
        KOPIBRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPIBROActionPerformed(evt);
            }
        });
        jPanel4.add(KOPIBRO);
        KOPIBRO.setBounds(30, 140, 120, 30);

        KOPIMOCHA.setText("Kopi Mocha");
        KOPIMOCHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPIMOCHAActionPerformed(evt);
            }
        });
        jPanel4.add(KOPIMOCHA);
        KOPIMOCHA.setBounds(30, 180, 120, 30);

        KOPICAP.setText("Kopi Capuccino");
        KOPICAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOPICAPActionPerformed(evt);
            }
        });
        jPanel4.add(KOPICAP);
        KOPICAP.setBounds(30, 220, 120, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(700, 100, 220, 370);

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("MAKANAN");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(60, 0, 110, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 60, 220, 40);

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("SPESIAL PLUS +");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(40, 0, 160, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(240, 60, 220, 40);

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));
        jPanel7.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Minuman Hangat / Es");
        jPanel7.add(jLabel9);
        jLabel9.setBounds(20, 0, 190, 30);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(470, 60, 220, 40);

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel8.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("ANEKA KOPI");
        jPanel8.add(jLabel27);
        jLabel27.setBounds(40, 0, 160, 30);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(700, 60, 220, 40);

        jPanel9.setBackground(new java.awt.Color(204, 0, 0));
        jPanel9.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("WARUNG NASI GORENG MEWAH SPESIAL PLUS +");
        jPanel9.add(jLabel35);
        jLabel35.setBounds(250, 10, 440, 30);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(10, 10, 910, 50);

        jPanel10.setBackground(new java.awt.Color(153, 255, 153));
        jPanel10.setLayout(null);

        Bayar.setText("Bayar");
        jPanel10.add(Bayar);
        Bayar.setBounds(20, 150, 80, 40);
        jPanel10.add(textHitung);
        textHitung.setBounds(40, 90, 130, 30);

        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel10.add(Hitung);
        Hitung.setBounds(20, 40, 170, 40);
        jPanel10.add(textBayar);
        textBayar.setBounds(120, 160, 140, 30);

        Kembali.setText("KEMBALIAN");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        jPanel10.add(Kembali);
        Kembali.setBounds(20, 210, 120, 40);

        textKembali.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel10.add(textKembali);
        textKembali.setBounds(120, 260, 170, 60);

        Hapus.setBackground(new java.awt.Color(255, 51, 51));
        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel10.add(Hapus);
        Hapus.setBounds(30, 340, 90, 30);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(930, 60, 300, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nasgorActionPerformed

    private void KOPIGINGSENGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPIGINGSENGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KOPIGINGSENGActionPerformed

    private void NASGORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NASGORActionPerformed
        // TODO add your handling code here:
        if(NASGOR.isSelected()== true) {
            nasgor.setEditable(true);
        }else{
            nasgor.setEditable(false);
            nasgor.setText("");
        }
    }//GEN-LAST:event_NASGORActionPerformed

    private void NASGORMAWUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NASGORMAWUTActionPerformed
        // TODO add your handling code here:
        if(NASGORMAWUT.isSelected()== true) {
            nasgormawut.setEditable(true);
        }else{
            nasgormawut.setEditable(false);
            nasgormawut.setText("");
        }
    }//GEN-LAST:event_NASGORMAWUTActionPerformed

    private void MIEGORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIEGORActionPerformed
        // TODO add your handling code here:
        if(MIEGOR.isSelected()== true) {
            miegor.setEditable(true);
        }else{
            miegor.setEditable(false);
            miegor.setText("");
        }
    }//GEN-LAST:event_MIEGORActionPerformed

    private void CAPCAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAPCAYActionPerformed
        // TODO add your handling code here:
        if(CAPCAY.isSelected()== true) {
            capcay.setEditable(true);
        }else{
            capcay.setEditable(false);
            capcay.setText("");
        }
    }//GEN-LAST:event_CAPCAYActionPerformed

    private void MIECAPCAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIECAPCAYActionPerformed
        // TODO add your handling code here:
        if(MIECAPCAY.isSelected()== true) {
            miecapcay.setEditable(true);
        }else{
            miecapcay.setEditable(false);
            miecapcay.setText("");
        }
    }//GEN-LAST:event_MIECAPCAYActionPerformed

    private void MIEBAKSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIEBAKSOActionPerformed
        // TODO add your handling code here:
        if(MIEBAKSO.isSelected()== true) {
            miebakso.setEditable(true);
        }else{
            miebakso.setEditable(false);
            miebakso.setText("");
        }
    }//GEN-LAST:event_MIEBAKSOActionPerformed

    private void JAMURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAMURActionPerformed
        // TODO add your handling code here:
        if(JAMUR.isSelected()== true) {
            jamur.setEditable(true);
        }else{
            jamur.setEditable(false);
            jamur.setText("");
        }
    }//GEN-LAST:event_JAMURActionPerformed

    private void BAKSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAKSOActionPerformed
        // TODO add your handling code here:
        if(BAKSO.isSelected()== true) {
            bakso.setEditable(true);
        }else{
            bakso.setEditable(false);
            bakso.setText("");
        }
    }//GEN-LAST:event_BAKSOActionPerformed

    private void ATIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATIActionPerformed
        // TODO add your handling code here:
        if(ATI.isSelected()== true) {
            ati.setEditable(true);
        }else{
            ati.setEditable(false);
            ati.setText("");
        }
    }//GEN-LAST:event_ATIActionPerformed

    private void SOSISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOSISActionPerformed
        // TODO add your handling code here:
        if(SOSIS.isSelected()== true) {
            sosis.setEditable(true);
        }else{
            sosis.setEditable(false);
            sosis.setText("");
        }
    }//GEN-LAST:event_SOSISActionPerformed

    private void USUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USUSActionPerformed
        // TODO add your handling code here:
        if(USUS.isSelected()== true) {
            usus.setEditable(true);
        }else{
            usus.setEditable(false);
            usus.setText("");
        }
    }//GEN-LAST:event_USUSActionPerformed

    private void TELURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TELURActionPerformed
        // TODO add your handling code here:
        if(TELUR.isSelected()== true) {
            telur.setEditable(true);
        }else{
            telur.setEditable(false);
            telur.setText("");
        }
    }//GEN-LAST:event_TELURActionPerformed

    private void KIKILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KIKILActionPerformed
        // TODO add your handling code here:
        if(KIKIL.isSelected()== true) {
            kikil.setEditable(true);
        }else{
            kikil.setEditable(false);
            kikil.setText("");
        }
    }//GEN-LAST:event_KIKILActionPerformed

    private void PETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PETEActionPerformed
        // TODO add your handling code here:
        if(PETE.isSelected()== true) {
            pete.setEditable(true);
        }else{
            pete.setEditable(false);
            pete.setText("");
        }
    }//GEN-LAST:event_PETEActionPerformed

    private void ABONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABONActionPerformed
        // TODO add your handling code here:
        if(ABON.isSelected()== true) {
            abon.setEditable(true);
        }else{
            abon.setEditable(false);
            abon.setText("");
        }
    }//GEN-LAST:event_ABONActionPerformed

    private void JERUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JERUKActionPerformed
        // TODO add your handling code here:
        if(JERUK.isSelected()== true) {
            jeruk.setEditable(true);
        }else{
            jeruk.setEditable(false);
            jeruk.setText("");
        }
    }//GEN-LAST:event_JERUKActionPerformed

    private void TEHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEHActionPerformed
        // TODO add your handling code here:
        if(TEH.isSelected()== true) {
            teh.setEditable(true);
        }else{
            teh.setEditable(false);
            teh.setText("");
        }
    }//GEN-LAST:event_TEHActionPerformed

    private void SUSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUSUActionPerformed
        // TODO add your handling code here:
        if(SUSU.isSelected()== true) {
            susu.setEditable(true);
        }else{
            susu.setEditable(false);
            susu.setText("");
        }
    }//GEN-LAST:event_SUSUActionPerformed

    private void JAHEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAHEActionPerformed
        // TODO add your handling code here:
        if(JAHE.isSelected()== true) {
            jahe.setEditable(true);
        }else{
            jahe.setEditable(false);
            jahe.setText("");
        }
    }//GEN-LAST:event_JAHEActionPerformed

    private void JAHEKRIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAHEKRIMActionPerformed
        // TODO add your handling code here:
        if(JAHEKRIM.isSelected()== true) {
            jahekrim.setEditable(true);
        }else{
            jahekrim.setEditable(false);
            jahekrim.setText("");
        }
    }//GEN-LAST:event_JAHEKRIMActionPerformed

    private void JOSHUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOSHUAActionPerformed
        // TODO add your handling code here:
        if(JOSHUA.isSelected()== true) {
            joshua.setEditable(true);
        }else{
            joshua.setEditable(false);
            joshua.setText("");
        }
    }//GEN-LAST:event_JOSHUAActionPerformed

    private void STMJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STMJActionPerformed
        // TODO add your handling code here:
        if(STMJ.isSelected()== true) {
            stmj.setEditable(true);
        }else{
            stmj.setEditable(false);
            stmj.setText("");
        }
    }//GEN-LAST:event_STMJActionPerformed

    private void SODAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SODAActionPerformed
        // TODO add your handling code here:
        if(SODA.isSelected()== true) {
            soda.setEditable(true);
        }else{
            soda.setEditable(false);
            soda.setText("");
        }
    }//GEN-LAST:event_SODAActionPerformed

    private void KOPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPIActionPerformed
        // TODO add your handling code here:
        if(KOPI.isSelected()== true) {
            kopi.setEditable(true);
        }else{
            kopi.setEditable(false);
            kopi.setText("");
        }
    }//GEN-LAST:event_KOPIActionPerformed

    private void KOPISUSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPISUSUActionPerformed
        // TODO add your handling code here:
        if(KOPISUSU.isSelected()== true) {
            kopisusu.setEditable(true);
        }else{
            kopisusu.setEditable(false);
            kopisusu.setText("");
        }
    }//GEN-LAST:event_KOPISUSUActionPerformed

    private void KOPISTMJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPISTMJActionPerformed
        // TODO add your handling code here:
        if(KOPISTMJ.isSelected()== true) {
            kopistmj.setEditable(true);
        }else{
            kopistmj.setEditable(false);
            kopistmj.setText("");
        }
    }//GEN-LAST:event_KOPISTMJActionPerformed

    private void KOPIBROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPIBROActionPerformed
        // TODO add your handling code here:
        if(KOPIBRO.isSelected()== true) {
            kopibro.setEditable(true);
        }else{
            kopibro.setEditable(false);
            kopibro.setText("");
        }
    }//GEN-LAST:event_KOPIBROActionPerformed

    private void KOPIMOCHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPIMOCHAActionPerformed
        // TODO add your handling code here:
        if(KOPIMOCHA.isSelected()== true) {
            kopimocha.setEditable(true);
        }else{
            kopimocha.setEditable(false);
            kopimocha.setText("");
        }
    }//GEN-LAST:event_KOPIMOCHAActionPerformed

    private void KOPICAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOPICAPActionPerformed
        // TODO add your handling code here:
        if(KOPICAP.isSelected()== true) {
            kopicap.setEditable(true);
        }else{
            kopicap.setEditable(false);
            kopicap.setText("");
        }
    }//GEN-LAST:event_KOPICAPActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int total = 0;
        if(NASGOR.isSelected()){
            String menu1 = nasgor.getText();
            int jumlah1 = Integer.parseInt(menu1);
            int hargamenu1 = jumlah1 * 10000;
            total = total + hargamenu1;
        }
        if(NASGORMAWUT.isSelected()){
            String menu2 = nasgormawut.getText();
            int jumlah2 = Integer.parseInt(menu2);
            int hargamenu2 = jumlah2 * 10000;
            total = total + hargamenu2;
        }
        if(MIEGOR.isSelected()){
            String menu3 = miegor.getText();
            int jumlah3 = Integer.parseInt(menu3);
            int hargamenu3 = jumlah3 * 10000;
            total = total + hargamenu3;
        }
        if(CAPCAY.isSelected()){
            String menu4 = capcay.getText();
            int jumlah4 = Integer.parseInt(menu4);
            int hargamenu4 = jumlah4 * 15000;
            total = total + hargamenu4;
        }
        if(MIECAPCAY.isSelected()){
            String menu5 = miecapcay.getText();
            int jumlah5 = Integer.parseInt(menu5);
            int hargamenu5 = jumlah5 * 20000;
            total = total + hargamenu5;
        }
        if(MIEBAKSO.isSelected()){
            String menu6 = miebakso.getText();
            int jumlah6 = Integer.parseInt(menu6);
            int hargamenu6 = jumlah6 * 20000;
            total = total + hargamenu6;
        }
        if(JAMUR.isSelected()){
            String plus1 = jamur.getText();
            int jumlah1 = Integer.parseInt(plus1);
            int hargaplus1 = jumlah1 * 3000;
            total = total + hargaplus1;
        }
        if(BAKSO.isSelected()){
            String plus2 = bakso.getText();
            int jumlah2 = Integer.parseInt(plus2);
            int hargaplus2 = jumlah2 * 4500;
            total = total + hargaplus2;
        }
        if(ATI.isSelected()){
            String plus3 = ati.getText();
            int jumlah3 = Integer.parseInt(plus3);
            int hargaplus3 = jumlah3 * 4500;
            total = total + hargaplus3;
        }
        if(USUS.isSelected()){
            String plus4 = usus.getText();
            int jumlah4 = Integer.parseInt(plus4);
            int hargaplus4 = jumlah4 * 3000;
            total = total + hargaplus4;
        }
        if(SOSIS.isSelected()){
            String plus5 = sosis.getText();
            int jumlah5 = Integer.parseInt(plus5);
            int hargaplus5 = jumlah5 * 4500;
            total = total + hargaplus5;
        }
        if(TELUR.isSelected()){
            String plus6 = telur.getText();
            int jumlah6 = Integer.parseInt(plus6);
            int hargaplus6 = jumlah6 * 5000;
            total = total + hargaplus6;
        }
        if(KIKIL.isSelected()){
            String plus7 = kikil.getText();
            int jumlah7 = Integer.parseInt(plus7);
            int hargaplus7 = jumlah7 * 4000;
            total = total + hargaplus7;
        }
        if(PETE.isSelected()){
            String plus8 = pete.getText();
            int jumlah8 = Integer.parseInt(plus8);
            int hargaplus8 = jumlah8 * 3500;
            total = total + hargaplus8;
        }
        if(ABON.isSelected()){
            String plus9 = abon.getText();
            int jumlah9 = Integer.parseInt(plus9);
            int hargaplus9 = jumlah9 * 3000;
            total = total + hargaplus9;
        }
        if(JERUK.isSelected()){
            String minum1 = jeruk.getText();
            int jumlah1 = Integer.parseInt(minum1);
            int hargaminum1 = jumlah1 * 2000;
            total = total + hargaminum1;
        }
        if(TEH.isSelected()){
            String minum2 = teh.getText();
            int jumlah2 = Integer.parseInt(minum2);
            int hargaminum2 = jumlah2 * 1500;
            total = total + hargaminum2;
        }
        if(SUSU.isSelected()){
            String minum3 = susu.getText();
            int jumlah3 = Integer.parseInt(minum3);
            int hargaminum3 = jumlah3 * 3000;
            total = total + hargaminum3;
        }
        if(JAHE.isSelected()){
            String minum4 = jahe.getText();
            int jumlah4 = Integer.parseInt(minum4);
            int hargaminum4 = jumlah4 * 3500;
            total = total + hargaminum4;
        }
        if(JAHEKRIM.isSelected()){
            String minum5 = jahekrim.getText();
            int jumlah5 = Integer.parseInt(minum5);
            int hargaminum5 = jumlah5 * 4000;
            total = total + hargaminum5;
        }
        if(JOSHUA.isSelected()){
            String minum6 = joshua.getText();
            int jumlah6 = Integer.parseInt(minum6);
            int hargaminum6 = jumlah6 * 5000;
            total = total + hargaminum6;
        }
        if(STMJ.isSelected()){
            String minum7 = stmj.getText();
            int jumlah7 = Integer.parseInt(minum7);
            int hargaminum7 = jumlah7 * 3500;
            total = total + hargaminum7;
        }
        if(SODA.isSelected()){
            String minum8 = soda.getText();
            int jumlah8 = Integer.parseInt(minum8);
            int hargaminum8 = jumlah8 * 5000;
            total = total + hargaminum8;
        }
        if(KOPI.isSelected()){
            String kopi1 = kopi.getText();
            int jumlah1 = Integer.parseInt(kopi1);
            int hargakopi1 = jumlah1 * 1500;
            total = total + hargakopi1;
        }
        if(KOPISUSU.isSelected()){
            String kopi2 = kopisusu.getText();
            int jumlah2 = Integer.parseInt(kopi2);
            int hargakopi2 = jumlah2 * 3000;
            total = total + hargakopi2;
        }
        if(KOPISTMJ.isSelected()){
            String kopi3 = kopistmj.getText();
            int jumlah3 = Integer.parseInt(kopi3);
            int hargakopi3 = jumlah3 * 4500;
            total = total + hargakopi3;
        }
        if(KOPIBRO.isSelected()){
            String kopi4 = kopibro.getText();
            int jumlah4 = Integer.parseInt(kopi4);
            int hargakopi4 = jumlah4 * 3000;
            total = total + hargakopi4;
        }
        if(KOPIMOCHA.isSelected()){
            String kopi5 = kopimocha.getText();
            int jumlah5 = Integer.parseInt(kopi5);
            int hargakopi5 = jumlah5 * 3000;
            total = total + hargakopi5;
        }
        if(KOPICAP.isSelected()){
            String kopi6 = kopicap.getText();
            int jumlah6 = Integer.parseInt(kopi6);
            int hargakopi6 = jumlah6 * 4000;
            total = total + hargakopi6;
        }
        if(KOPIGINGSENG.isSelected()){
            String kopi7 = kopigingseng.getText();
            int jumlah7 = Integer.parseInt(kopi7);
            int hargakopi7 = jumlah7 * 3000;
            total = total + hargakopi7;
        }
        textHitung.setText("" + total);
    }//GEN-LAST:event_HitungActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        
        nasgor.setText("");
        NASGOR.setSelected(false);
        
        
        nasgormawut.setText("");
        NASGORMAWUT.setSelected(false);
        
        
        miegor.setText("");
        MIEGOR.setSelected(false);
        
        
        capcay.setText("");
        CAPCAY.setSelected(false);
        
        
        miecapcay.setText("");
        MIECAPCAY.setSelected(false);
        
       
        miebakso.setText("");
        MIEBAKSO.setSelected(false);
        
       
        jamur.setText("");
        JAMUR.setSelected(false);
        
        
        bakso.setText("");
        BAKSO.setSelected(false);
        
        
        ati.setText("");
        ATI.setSelected(false);
        
      
        sosis.setText("");
        SOSIS.setSelected(false);
        
       
        usus.setText("");
        USUS.setSelected(false);
        
     
        telur.setText("");
        TELUR.setSelected(false);
        
       
        kikil.setText("");
        KIKIL.setSelected(false);
        
      
        pete.setText("");
        PETE.setSelected(false);
        
       
        abon.setText("");
        ABON.setSelected(false);
        
       
        jeruk.setText("");
        JERUK.setSelected(false);
        
       
        teh.setText("");
        TEH.setSelected(false);
        
        
        susu.setText("");
        SUSU.setSelected(false);
        
       
        jahe.setText("");
        JAHE.setSelected(false);
        
       
        jahekrim.setText("");
        JAHEKRIM.setSelected(false);
        
        
        joshua.setText("");
        JOSHUA.setSelected(false);
        
       
        stmj.setText("");
        STMJ.setSelected(false);
        
        
        soda.setText("");
        SODA.setSelected(false);
        
       
        kopi.setText("");
        KOPI.setSelected(false);
        
     
        kopisusu.setText("");
        KOPISUSU.setSelected(false);
        
       
        kopistmj.setText("");
        KOPISTMJ.setSelected(false);
        
       
        kopibro.setText("");
        KOPIBRO.setSelected(false);
        
        
        kopimocha.setText("");
        KOPIMOCHA.setSelected(false);
        
       
        kopicap.setText("");
        KOPICAP.setSelected(false);
        
      
        kopigingseng.setText("");
        KOPIGINGSENG.setSelected(false);
        
        textHitung.setText("");
        textKembali.setText("");
        textBayar.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        membayar = Integer.parseInt(textBayar.getText());
        jumlah = Integer.parseInt(textHitung.getText());
        kembali = (membayar - jumlah);
        textKembali.setText(String.valueOf(kembali));
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ABON;
    private javax.swing.JCheckBox ATI;
    private javax.swing.JCheckBox BAKSO;
    private javax.swing.JButton Bayar;
    private javax.swing.JCheckBox CAPCAY;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Hitung;
    private javax.swing.JCheckBox JAHE;
    private javax.swing.JCheckBox JAHEKRIM;
    private javax.swing.JCheckBox JAMUR;
    private javax.swing.JCheckBox JERUK;
    private javax.swing.JCheckBox JOSHUA;
    private javax.swing.JCheckBox KIKIL;
    private javax.swing.JCheckBox KOPI;
    private javax.swing.JCheckBox KOPIBRO;
    private javax.swing.JCheckBox KOPICAP;
    private javax.swing.JCheckBox KOPIGINGSENG;
    private javax.swing.JCheckBox KOPIMOCHA;
    private javax.swing.JCheckBox KOPISTMJ;
    private javax.swing.JCheckBox KOPISUSU;
    private javax.swing.JButton Kembali;
    private javax.swing.JCheckBox MIEBAKSO;
    private javax.swing.JCheckBox MIECAPCAY;
    private javax.swing.JCheckBox MIEGOR;
    private javax.swing.JCheckBox NASGOR;
    private javax.swing.JCheckBox NASGORMAWUT;
    private javax.swing.JCheckBox PETE;
    private javax.swing.JCheckBox SODA;
    private javax.swing.JCheckBox SOSIS;
    private javax.swing.JCheckBox STMJ;
    private javax.swing.JCheckBox SUSU;
    private javax.swing.JCheckBox TEH;
    private javax.swing.JCheckBox TELUR;
    private javax.swing.JCheckBox USUS;
    private javax.swing.JTextField abon;
    private javax.swing.JTextField ati;
    private javax.swing.JTextField bakso;
    private javax.swing.JTextField capcay;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jahe;
    private javax.swing.JTextField jahekrim;
    private javax.swing.JTextField jamur;
    private javax.swing.JTextField jeruk;
    private javax.swing.JTextField joshua;
    private javax.swing.JTextField kikil;
    private javax.swing.JTextField kopi;
    private javax.swing.JTextField kopibro;
    private javax.swing.JTextField kopicap;
    private javax.swing.JTextField kopigingseng;
    private javax.swing.JTextField kopimocha;
    private javax.swing.JTextField kopistmj;
    private javax.swing.JTextField kopisusu;
    private javax.swing.JTextField miebakso;
    private javax.swing.JTextField miecapcay;
    private javax.swing.JTextField miegor;
    private javax.swing.JTextField nasgor;
    private javax.swing.JTextField nasgormawut;
    private javax.swing.JTextField pete;
    private javax.swing.JTextField soda;
    private javax.swing.JTextField sosis;
    private javax.swing.JTextField stmj;
    private javax.swing.JTextField susu;
    private javax.swing.JTextField teh;
    private javax.swing.JTextField telur;
    private javax.swing.JTextField textBayar;
    private javax.swing.JTextField textHitung;
    private javax.swing.JTextField textKembali;
    private javax.swing.JTextField usus;
    // End of variables declaration//GEN-END:variables
}
